spring:
  application:
    name: taskmaster

  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/FREEPDB1
    username: taskmaster
    password: securePassword123
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.OracleDialect

  data:
    web:
      pageable:
        one-indexed-parameters: true

jwt:
  secret: "5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437"
  expiration: 7200000 # 2 hours in milliseconds